[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "archivum"
version = "0.1.0"
description = "Shared modules for the Archivum project"
requires-python = ">=3.12"
dependencies = [
    "llama-cloud>=2",
    "python-dotenv",
    "supabase",
    "azure-identity",
    "azure-appconfiguration>=1.7.0",
    "azure-appconfiguration-provider",
    "azure-keyvault-secrets",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["archivum*"]
